### ISSUE TITLE
Fix for MetaVideo regex

### ISSUE THREAD

**Issue by Sausbolle** [AydinAdn/MediaToolkit#108]
Could you consider updating (after double-checking the regex) the meta info regex so it works on some Stream formats that has more than one comma separated `ColorModel` in the video meta info.

File: `./Utils/RegexEngine.cp` Line: `32`
```
new Regex(@"Video:\s*([^,]*),\s*([^,]*,?[^,]*?),?\s*(?=[0-9]*x[0-9]*)([0-9]*x[0-9]*)")
```` 
Change it to:
```
new Regex(@"Video:\s*([^,]*),\s*([^,]*(?:,?[^,]*?)*?),?\s*(?=[0-9]*x[0-9]*)([0-9]*x[0-9]*)")
```` 

Example of Video meta info that will fail in old/original Regex
`Stream #0:0: Video: vp8, yuv420p(tv, bt709, progressive), 640x360, SAR 1:1 DAR 16:9, 25 fps, 25 tbr, 1k tbn, 1k tbc (default)`

**Comment by AydinAdn** [comment]
There's no point because the entire project is being updated and the current way of doing things will never be able to accommodate every type of conversion. 

The update on the way is using ffprobe to gather metadata on media and it contains a lot more information and accommodates a much wider range of scenarios, you can check it out in the MajorRefactoring branch. (the read me of that branch hasn't been updated however there's test projects in it that demonstrates its usages)
