### ISSUE TITLE
Command line argument Support

### ISSUE THREAD

**Issue by sur3d** [AydinAdn/MediaToolkit#47]
Hey! First of all let me tell you that I found this wrapper SUPER useful :)

As per the README MaediaToolkit "supports custom FFmpeg command line arguments"
I've been trying to speed up the video (to create a timelapse like one) using [this ](https://trac.ffmpeg.org/wiki/How%20to%20speed%20up%20/%20slow%20down%20a%20video)
but I can't find any example of a command line invocation. Having this'd be very useful

**Comment by AydinAdn** [comment]
Always great to know it's helping people. 

The implementation should already be there... I've been kicking the can down the road since forever but will definitely update the readme at some point...

The method you're looking for is `Engine.CustomCommand(string ffmpegCommand)`

So instead of `Convert`, you would use the method above (and yes it needs renaming, because its ambiguous as to whether you still need to call convert afterwards, another can far down the road)

**Comment by sur3d** [comment]
Aydin, thank you so much for your reply!
I keep bangin my head against the wall, cause I tried

 using (var engine = new Engine())
                {                   
                    engine.CustomCommand(
                          "ffmpeg -i \"C:\\Users\\ale\\Documents\\in.mp4\" -filter:v \"setpts = 3 * PTS\" C:\\Users\\ale\\Documents\\out.mp4");               
              }

But nothing happened (I don't get any exception either!)
No, when I try the same string in the command line:

ffmpeg -i "C:\Users\ale\Documents\in.mp4" -filter:v "setpts=3*PTS" "C:\Users\ale\Documents\out.mp4"

It works perfectly. What am I doing wrong?

**Comment by jcd03** [comment]
I know this is an old question but I ran across this myself. My problem was including the "ffmpeg" in the custom command.

The source code already calls 'ffmpeg.exe' when you include it in your project. So the final code should just be....

> using (var engine = new Engine())
> {
> engine.CustomCommand(
> "-i "C:\Users\ale\Documents\in.mp4" -filter:v \"setpts = 3 * PTS\" C:\Users\ale\Documents\out.mp4");
> }

of course escape your quotes in the string.
